[package]
name = "operator-wallet"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
algebra.workspace = true

bdk_bitcoind_rpc.workspace = true
bdk_wallet.workspace = true
tokio.workspace = true
tracing.workspace = true
