[package]
name = "secret-service"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin.workspace = true
blake3.workspace = true
musig2.workspace = true
rcgen = "0.13.2"
rustls-pemfile = "2.2.0"
secret-service-proto = { version = "0.1.0", path = "../secret-service-proto" }
secret-service-server = { version = "0.1.0", path = "../secret-service-server" }
serde.workspace = true
sled = "0.34.7"
strata-key-derivation = { git = "https://github.com/alpenlabs/strata", version = "0.1.0" }

tokio.workspace = true
toml = "0.8.19"
tracing.workspace = true
tracing-subscriber.workspace = true
