[package]
name = "secret-service"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin.workspace = true
blake3.workspace = true
hkdf = "0.12.4"
musig2.workspace = true
parking_lot.workspace = true
rand.workspace = true
rcgen = "0.13.2"
rkyv.workspace = true
rustls-pemfile = "2.2.0"
secret-service-proto = { version = "0.1.0", path = "../secret-service-proto" }
secret-service-server = { version = "0.1.0", path = "../secret-service-server" }
serde.workspace = true
sha2.workspace = true
sled = "0.34.7"
strata-bridge-primitives.workspace = true
strata-key-derivation = { git = "https://github.com/alpenlabs/strata", version = "0.1.0" }
terrors.workspace = true

tokio.workspace = true
toml = "0.8.19"
tracing.workspace = true
tracing-subscriber.workspace = true
