[package]
name = "algebra"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
futures.workspace = true
proptest.workspace = true
tokio.workspace = true

[dev-dependencies]
tracing.workspace = true