[package]
edition = "2021"
name = "strata-cli"
version = "0.1.0"

[[bin]]
name = "strata"
path = "src/main.rs"

[dependencies]
aes-gcm-siv = "0.11.1"
alloy = { version = "0.3.5", features = [
  "std",
  "rpc-client-ws",
  "network",
  "signers",
  "signer-local",
  "providers",
  "rpc-types",
] }
argh.workspace = true
argon2 = "0.5.3"
bdk_esplora = { version = "0.19.0", features = [
  "async-https",
  "async-https-rustls",
], default-features = false }
bdk_wallet = { version = "1.0.0-beta.5", features = ["rusqlite"] }
bip39 = { version = "2.0.0", features = ["all-languages"] }
config = { version = "0.14.0", default-features = false, features = ["toml"] }
console = "0.15.8"
dialoguer = "0.11.0"
directories = "5.0.1"
indicatif = { version = "0.17.8", features = ["improved_unicode", "tokio"] }
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
sha2 = { version = "0.10.8", features = ["loongarch64_asm"] }
shrex = { workspace = true, features = ["serde"] }
sled = "0.34.7"
strata-bridge-tx-builder.workspace = true
terrors.workspace = true
tokio.workspace = true

# sha2 fails to compile on windows with the "asm" feature
[target.'cfg(not(target_os = "windows"))'.dependencies]
sha2 = { version = "0.10.8", features = ["asm", "loongarch64_asm"] }

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
keyring = { version = "3.3.0", default-features = false, features = [
  "apple-native",
] }

[target.'cfg(target_os = "windows")'.dependencies]
keyring = { version = "3.3.0", default-features = false, features = [
  "windows-native",
] }
