#!/usr/bin/env python3
"""render_sp1_proof_summary.py — Surface raw SP1 proof request logs in the job summary.

Called by .github/workflows/functional-sp1-proofs.yml after the functional test
step completes (pass or fail). Scans every log file under functional-tests/_dd
for `sp1_sdk::network::prover` lines — the per-request block the SP1 network
prover emits (strategy, proof mode, circuit version, timeout, cycle limit, gas
limit, request ID + tx, explorer URL) — and writes them verbatim to the job
summary, grouped per service.

By default all operator logs are scanned: for fn_bridge_proof the proof is
generated by whichever operator the claim is assigned to, and only that
operator's log contains the prover lines. Set SP1_LOG_SERVICES to restrict the
scan — e.g. fn_counterproof sets `operator-1` because operator-0 is the
dishonest poster (faulty claim/proof via dev-cli, no real proving) and the
operator-1 watchtower is the one making the real SP1 counterproof request.

Expected env vars:
    TEST_FILE             — functional test name, used for the heading
    SP1_LOG_SERVICES      — optional comma-separated path components; when set,
                            only log files whose path contains one of them as
                            an exact component are scanned (e.g. "operator-1"
                            matches <run-id>/<env>/operator-1/bridge_node/...)
    GITHUB_STEP_SUMMARY   — path to the live job-summary file injected by GHA

Output:
    GITHUB_STEP_SUMMARY   — the markdown is appended to the live job summary
    stdout                — the same content, so it is greppable in the job log

Always exits 0 — missing logs or zero matches must never fail the job.
"""

import os
import re
import sys
from pathlib import Path

DATA_DIR = Path("functional-tests/_dd")

# Lines emitted by the SP1 network prover, e.g.
#   2026-06-06T08:16:10.046532Z  INFO sp1_sdk::network::prover: ├─ Cycle limit: 10179872 cycles
PROVER_MARKER = "sp1_sdk::network::prover"

# Strip the leading timestamp so lines start at the log level.
LINE_RE = re.compile(r"^.*?\b(TRACE|DEBUG|INFO|WARN|ERROR)\b")

# Explorer URLs repeated outside the code fence so they are clickable
# (GitHub does not linkify URLs inside fenced code blocks).
URL_RE = re.compile(r"View request status at: (https://\S+)")


def collect_prover_lines(logfile: Path) -> list[str]:
    """Return the `sp1_sdk::network::prover` lines of a log file, timestamps stripped."""
    lines: list[str] = []
    try:
        text = logfile.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return lines
    for line in text.splitlines():
        if PROVER_MARKER not in line:
            continue
        lines.append(LINE_RE.sub(r"\1", line).strip())
    return lines


def main() -> None:
    test_file = os.environ.get("TEST_FILE", "unknown")
    # Optional allowlist of path components, e.g. "operator-1". Exact component
    # match so "operator-1" can never match "operator-10".
    services = [s.strip() for s in os.environ.get("SP1_LOG_SERVICES", "").split(",") if s.strip()]

    sections: list[str] = [f"## SP1 proof requests — {test_file}", ""]
    found = False

    for logfile in sorted(DATA_DIR.rglob("*.log")):
        rel = logfile.relative_to(DATA_DIR)
        if services and not any(s in rel.parts for s in services):
            continue
        prover_lines = collect_prover_lines(logfile)
        if not prover_lines:
            continue
        found = True
        # Service logs live at <run-id>/<env>/operator-<N>/bridge_node/service.log;
        # label with the dir path minus the run-id so the operator is visible.
        service = "/".join(rel.parts[1:-1]) or rel.parts[0]
        sections += [f"### {service}", "", "```", *prover_lines, "```", ""]
        urls = [m.group(1) for line in prover_lines if (m := URL_RE.search(line))]
        sections += [f"🔗 {url}" for url in urls]
        if urls:
            sections.append("")

    if not found:
        sections += ["_No SP1 proof requests found in logs._", ""]

    markdown = "\n".join(sections) + "\n"
    print(markdown)

    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary_path:
        with open(summary_path, "a", encoding="utf-8") as f:
            f.write(markdown)


if __name__ == "__main__":
    main()
    sys.exit(0)
