#!/usr/bin/env python3
"""render_sp1_proof_summary.py — Surface raw SP1 proof request logs in the job summary.

Called by .github/workflows/functional-sp1-proofs.yml after the functional test
step completes (pass or fail). Scans every log file under functional-tests/_dd
for `sp1_sdk::network::prover` lines — the per-request block the SP1 network
prover emits (strategy, proof mode, circuit version, timeout, cycle limit, gas
limit, request ID + tx, explorer URL) — and writes them verbatim to the job
summary, grouped per service.

All operator logs are scanned (not just operator 0): the proof is generated by
whichever operator the claim is assigned to, and only that operator's log
contains the prover lines. The per-service heading shows which operator proved.

Expected env vars:
    TEST_FILE             — functional test name, used for the heading
    GITHUB_STEP_SUMMARY   — path to the live job-summary file injected by GHA

Output:
    GITHUB_STEP_SUMMARY   — the markdown is appended to the live job summary
    stdout                — the same content, so it is greppable in the job log

Always exits 0 — missing logs or zero matches must never fail the job.
"""

import os
import re
import sys
from pathlib import Path

DATA_DIR = Path("functional-tests/_dd")

# Lines emitted by the SP1 network prover, e.g.
#   2026-06-06T08:16:10.046532Z  INFO sp1_sdk::network::prover: ├─ Cycle limit: 10179872 cycles
PROVER_MARKER = "sp1_sdk::network::prover"

# Strip the leading timestamp so lines start at the log level.
LINE_RE = re.compile(r"^.*?\b(TRACE|DEBUG|INFO|WARN|ERROR)\b")

# Explorer URLs repeated outside the code fence so they are clickable
# (GitHub does not linkify URLs inside fenced code blocks).
URL_RE = re.compile(r"View request status at: (https://\S+)")


def collect_prover_lines(logfile: Path) -> list[str]:
    """Return the `sp1_sdk::network::prover` lines of a log file, timestamps stripped."""
    lines = []
    try:
        text = logfile.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return lines
    for line in text.splitlines():
        if PROVER_MARKER not in line:
            continue
        lines.append(LINE_RE.sub(r"\1", line).strip())
    return lines


def main() -> None:
    test_file = os.environ.get("TEST_FILE", "unknown")

    sections: list[str] = [f"## SP1 proof requests — {test_file}", ""]
    found = False

    for logfile in sorted(DATA_DIR.rglob("*.log")):
        prover_lines = collect_prover_lines(logfile)
        if not prover_lines:
            continue
        found = True
        # Service logs live at <run-id>/<service>/service.log; test logs at
        # <run-id>/logs/<test>.log — the parent dir name identifies the source.
        service = logfile.parent.name
        sections += [f"### {service}", "", "```", *prover_lines, "```", ""]
        urls = [m.group(1) for line in prover_lines if (m := URL_RE.search(line))]
        sections += [f"🔗 {url}" for url in urls]
        if urls:
            sections.append("")

    if not found:
        sections += ["_No SP1 proof requests found in logs._", ""]

    markdown = "\n".join(sections) + "\n"
    print(markdown)

    summary_path = os.environ.get("GITHUB_STEP_SUMMARY")
    if summary_path:
        with open(summary_path, "a", encoding="utf-8") as f:
            f.write(markdown)


if __name__ == "__main__":
    main()
    sys.exit(0)
