x-base-secret-service: &base-secret-service
  image: secret-service:latest
  build:
    context: .
    dockerfile: ./docker/secret-service/Dockerfile
  environment:
    - SECRET_SERVICE_DEV=0 # use ./docker/gen_s2_tls.sh to gen tls certs
    - RUST_LOG=info

x-base-bridge-node: &base-bridge-node
  image: strata-bridge:latest
  build:
    context: .
    dockerfile: ./docker/alpen-bridge/Dockerfile
  environment:
    - MODE=operator
    - RUST_LOG=info,duty_tracker=debug,bitvm=error,btc_notify=warn,duty_tracker::contract_persister=warn,duty_tracker::stake_chain_persister=warn,strata_p2p=error
    - LOG_FILE=0
    - LOG_LINE_NUM=0
    - RUST_BACKTRACE=full
    - MULTI_THREAD_GRAPH_GEN=0 # 1 in order to use an OS thread per graph generation
    - SP1_PROVER=$SP1_PROVER
    - SP1_PROOF_STRATEGY=$SP1_PROOF_STRATEGY
    - NETWORK_RPC_URL=$NETWORK_RPC_URL
    - NETWORK_PRIVATE_KEY=$NETWORK_PRIVATE_KEY
  depends_on:
    - bitcoind

services:
  secret-service-1:
    <<: *base-secret-service
    ports:
      - 11000:3000
    volumes:
      - ./docker/vol/secret-service-1:/app
    networks:
      bridge:
        ipv4_address: 172.28.1.5
  bridge-1:
    <<: *base-bridge-node
    ports:
      - 15678:5678
      - 15679:5679
      - 13000:3000
    volumes:
      - ./docker/vol/alpen-bridge-1:/app
      - ./migrations:/app/migrations
    networks:
      bridge:
        ipv4_address: 172.28.0.5

  secret-service-2:
    <<: *base-secret-service
    ports:
      - 21000:3000
    volumes:
      - ./docker/vol/secret-service-2:/app
    networks:
      bridge:
        ipv4_address: 172.28.1.6
  bridge-2:
    <<: *base-bridge-node
    ports:
      - 25678:5678
      - 25679:5679
      - 23000:3000
    volumes:
      - ./docker/vol/alpen-bridge-2:/app
      - ./migrations:/app/migrations
    networks:
      bridge:
        ipv4_address: 172.28.0.6

  secret-service-3:
    <<: *base-secret-service
    ports:
      - 31000:3000
    volumes:
      - ./docker/vol/secret-service-3:/app
    networks:
      bridge:
        ipv4_address: 172.28.1.7
  bridge-3:
    <<: *base-bridge-node
    ports:
      - 35678:5678
      - 35679:5679
      - 33000:3000
    volumes:
      - ./docker/vol/alpen-bridge-3:/app
      - ./migrations:/app/migrations
    networks:
      bridge:
        ipv4_address: 172.28.0.7

  bitcoind:
    image: bitcoin/bitcoin:29
    volumes:
      - ./docker/bitcoin/entrypoint.sh:/entrypoint.sh
    ports:
      - 18443:18443
      - 18444:18444
      - 28332:28332
      - 28333:28333
      - 28334:28334
      - 28335:28335
      - 28336:28336
    # see logs from the bridge node to populate these env vars
    #
    # Example:
    #
    # INFO operator_wallet: crates/operator-wallet/src/lib.rs:87: general wallet address: bcrt1pjrd2pungnh6ae7acw9dt92t5hj8gkn2gh8nuwu2r3kakklkswqrquyus8n
    # INFO operator_wallet: crates/operator-wallet/src/lib.rs:95: stakechain wallet address: bcrt1pga206rnnd9vchqvs5s0gax4v99pdzlml470f3tfw8nfaemmmu0wsjru24g
    environment:
      - GENERAL_WALLET_1=$GENERAL_WALLET_1
      - STAKE_CHAIN_WALLET_1=$STAKE_CHAIN_WALLET_1
      - GENERAL_WALLET_2=$GENERAL_WALLET_2
      - STAKE_CHAIN_WALLET_2=$STAKE_CHAIN_WALLET_2
      - GENERAL_WALLET_3=$GENERAL_WALLET_3
      - STAKE_CHAIN_WALLET_3=$STAKE_CHAIN_WALLET_3
      - AUTOMINE=5 # every 5 seconds, set to 0 to disable auto generating blocks, keep in alignment with `block_time` in sidesystem params
    networks:
      - bridge

networks:
  bridge:
    ipam:
      config:
        - subnet: 172.28.0.0/16
