services:
  secret-service:
    image: secret-service:latest
    build:
      context: .
      dockerfile: ./docker/secret-service/Dockerfile
    environment:
      - SECRET_SERVICE_DEV=1
    volumes:
      - ./docker/vol/secret-service:/app
