[toolchain]
# update this after https://github.com/rust-lang/rust/issues/134044 is fixed.
channel = "nightly-2025-04-02"
components = [
  "cargo",
  "clippy",
  "rustc",
  "rustfmt",
  "rust-analyzer",
  "rust-docs",
  "rust-src",
  "rust-std",
  # "miri" # some of the secp256k1 FFIs fail with miri
]
