[toolchain]
channel = "nightly-2025-07-01"
components = [
  "cargo",
  "clippy",
  "rustc",
  "rustfmt",
  "rust-analyzer",
  "rust-docs",
  "rust-src",
  "rust-std",
  # "miri" # some of the secp256k1 FFIs fail with miri
]
