[package]
name = "strata-bridge-proof-protocol2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
arbitrary.workspace = true
bitcoin.workspace = true
borsh.workspace = true
secp256k1.workspace = true
thiserror.workspace = true

strata-l1tx.workspace = true
strata-primitives.workspace = true
strata-proofimpl-btc-blockspace.workspace = true
strata-state.workspace = true
strata-zkvm.workspace = true

[dev-dependencies]
strata-test-utils = { git = "https://github.com/alpenlabs/strata" }
rand = { version = "0.8.5", features = ["getrandom", "std_rng"] }
