[package]
name = "strata-bridge-proof-protocol2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
arbitrary.workspace = true
bitcoin.workspace = true
borsh.workspace = true
secp256k1.workspace = true
thiserror.workspace = true

strata-primitives = { git = "https://github.com/alpenlabs/strata" }
strata-proofimpl-btc-blockspace = { git = "https://github.com/alpenlabs/strata" }
strata-state = { git = "https://github.com/alpenlabs/strata" }
strata-tx-parser = { git = "https://github.com/alpenlabs/strata" }
strata-zkvm = { git = "https://github.com/alpenlabs/strata" }

[dev-dependencies]
strata-test-utils = { git = "https://github.com/alpenlabs/strata" }
rand = { version = "0.8.5", features = ["getrandom", "std_rng"] }
