[package]
edition = "2021"
name = "strata-proofimpl-bitvm-bridge"
version = "0.1.0"

[dependencies]
bitcoin = { version = "=0.32.3", features = ["serde"] }
borsh.workspace = true
serde = { workspace = true, features = ["derive"] }
strata-primitives.workspace = true
strata-state.workspace = true
strata-zkvm.workspace = true
