[package]
edition = "2021"
name = "alpen-bridge-params"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
bitcoin.workspace = true
serde.workspace = true

[dev-dependencies]
toml.workspace = true
