x-base-client: &base-client
  build:
    context: ../
    dockerfile: ./docker/client/Dockerfile
  image: "strata_client:v0.1.0"
  networks:
    - strata_network

x-base-reth: &base-reth
  build:
    context: ../
    dockerfile: ./docker/reth/Dockerfile
  image: "strata_reth:v0.1.0"
  networks:
    - strata_network

x-base-bridge-client: &base-bridge-client
  build:
    context: ../
    dockerfile: ./docker/bridge-client/Dockerfile
  image: "strata_bridge_client:v0.1.0"
  restart: always
  environment:
    BTC_URL: "http://bitcoind:18443"
    BTC_USER: rpcuser
    BTC_PASS: rpcpassword
    RPC_HOST: "0.0.0.0"
    RPC_PORT: 4781 # default
    ROLLUP_URL: "ws://sequencer:8432"
    MAX_DUTY_RETRIES: 3 # for local environments
    DATADIR: .data # default
  networks:
    - strata_network
  depends_on:
    - sequencer

services:
  reth:
    <<: *base-reth
    container_name: strata_reth
    environment:
      JWTSECRET: "configs/jwt.hex"
    volumes:
      - ./.data/data-reth:/app/reth
      - ./configs:/app/configs
      # - ./configs/p2p.seq.hex:/app/p2p.hex
      # - ./configs/jwt.seq.hex:/app/jwt.hex
    command:
      - "--enable-witness-gen"
    ports:
      # - 8551:8551
      - 8545:8545
      - 8546:8546

  reth-fn:
    <<: *base-reth
    container_name: strata_reth_fn
    environment:
      JWTSECRET: "configs/jwt.fn.hex"
    command:
      - "--sequencer-http"
      - "http://strata_reth:8545"

    volumes:
      - ./.data/data-reth-fn:/app/reth
      - ./configs:/app/configs
      # - ./configs/p2p.fn.hex:/app/p2p.hex
      # - ./configs/jwt.fn.hex:/app/jwt.hex
    ports:
      # - 8561:8551
      - 8555:8545
      - 8556:8546

  sequencer:
    <<: *base-client
    container_name: strata_sequencer
    ports:
      - 8432:8432
    environment:
      CONFIG_PATH: "configs/config.seq.toml"
      PARAM_PATH: "configs/params.json"
    volumes:
      - ./.data/data-sequencer:/app/data
      - ./configs:/app/configs
      # - ./configs/config.seq.toml:/app/config.toml
      # - ./configs/params.devnet.json:/app/params.json
      # - ./configs/sequencer.key:/app/sequencer.key
      # - ./configs/jwt.seq.hex:/app/jwt.hex
    depends_on:
      - bitcoind
      - reth

  fullnode:
    <<: *base-client
    container_name: strata_fullnode
    ports:
      - 8433:8432
    environment:
      CONFIG_PATH: "configs/config.fn.toml"
      PARAM_PATH: "configs/params.json"
    volumes:
      - ./.data/data-fullnode:/app/data
      - ./configs:/app/configs
      # - ./configs/params.json:/app/params.json
      # - ./configs/jwt.fn.hex:/app/jwt.hex
      # need to wait for sequencer to start
    entrypoint: /bin/sh -c "sleep 10 && /app/entrypoint.sh \"$@\"" --
    depends_on:
      - bitcoind
      - reth-fn
      - sequencer

  bitcoind:
    build:
      context: ./bitcoind/
    image: "strata_bitcoind:v0.1.0"
    environment:
      RPC_ALLOW_IP: "0.0.0.0/0"
      BITCOIND_RPC_USER: rpcuser
      BITCOIND_RPC_PASSWORD: rpcpassword
      BITCOIND_WALLET: default
    container_name: strata_bitcoind
    volumes:
      - ./.data/data-bitcoind:/root/.bitcoin/
    ports:
      - "18443:18443"
    networks:
      - strata_network

  bridge-client-1:
    <<: *base-bridge-client
    container_name: bridge-client-1
    volumes:
      - ./configs/operator1.bin:/app/.secrets/xpriv.bin
      - ./.data/bridge-client-1:/app/.data
    ports:
      - 4781:4781

  bridge-client-2:
    <<: *base-bridge-client
    container_name: bridge-client-2
    volumes:
      - ./configs/operator2.bin:/app/.secrets/xpriv.bin
      - ./.data/bridge-client-2:/app/.data
    ports:
      - 4782:4781

networks:
  strata_network:
    driver: bridge
    name: strata_network
