[package]
name = "mi6-server"
version = "0.1.0"
edition = "2021"

[dependencies]
kanal.workspace = true
mi6-proto = { version = "0.1.0", path = "../mi6-proto" }
quinn.workspace = true
rkyv.workspace = true
terrors.workspace = true
tokio.workspace = true
tracing.workspace = true
