[package]
edition = "2021"
name = "strata-bridge-guest"
version = "0.1.0"

[workspace]

[dependencies]
strata-bridge-proof-protocol = { path = "../../crates/bridge-proof/protocol" }
zkaleido-sp1-guest-env = { git = "https://github.com/alpenlabs/zkaleido", tag = "v0.1.0-alpha-rc11", features = [
  "blake3",
] }

[patch.crates-io]
secp256k1 = { git = "https://github.com/sp1-patches/rust-secp256k1", tag = "patch-0.29.1-sp1-5.0.0" }
sha2-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", tag = "patch-sha2-0.10.8-sp1-4.0.0" }
