[package]
name = "memory_pprof"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
axum = "0.7"
jemalloc_pprof = { version = "0.8", features = ["flamegraph"] }
tokio.workspace = true
tracing.workspace = true
