[package]
edition = "2024"
name = "strata-mosaic-client"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
algebra.workspace = true
strata-bridge-primitives.workspace = true
strata-mosaic-client-api.workspace = true

mosaic-rpc-api.workspace = true
mosaic-rpc-types.workspace = true

async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
bitcoin.workspace = true
blake3.workspace = true
bn = { package = "substrate-bn", version = "0.6.0" }
hex.workspace = true
sha2.workspace = true
ssz.workspace = true
strata-bridge-counterproof.workspace = true
sp1-verifier.workspace = true
thiserror.workspace = true
zkaleido.workspace = true
zkaleido-sp1-groth16-verifier.workspace = true
