[package]
edition = "2024"
name = "strata-mosaic-client"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
algebra.workspace = true
strata-bridge-primitives.workspace = true
strata-mosaic-client-api.workspace = true

mosaic-rpc-api.workspace = true
mosaic-rpc-types.workspace = true

async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
ark-ec = "0.6.0"
ark-ff = "0.6.0"
ark-secp256k1 = "0.6.0"
bitcoin.workspace = true
bn = { package = "substrate-bn", version = "0.6.0" }
hex.workspace = true
mosaic-adaptor-sigs = { git = "https://github.com/alpenlabs/mosaic", tag = "v0.3.0-rc.2" }
rand.workspace = true
sha2.workspace = true
sp1-verifier.workspace = true
zkaleido-sp1-groth16-verifier.workspace = true
