[package]
edition = "2021"
name = "dev-bridge"
version = "0.1.0"

[lints]
workspace = true

[[bin]]
name = "dev-bridge"
path = "src/main.rs"

[dependencies]
strata-bridge-agent.workspace = true
strata-bridge-common.workspace = true
strata-bridge-db.workspace = true
strata-bridge-primitives.workspace = true
strata-bridge-rpc.workspace = true
strata-primitives.workspace = true
strata-rpc-api.workspace = true

anyhow.workspace = true
async-trait.workspace = true
bitcoin.workspace = true
bitcoind-async-client.workspace = true
chrono.workspace = true
clap.workspace = true
jsonrpsee = { workspace = true, features = ["client", "server"] }
rand.workspace = true
secp256k1 = { workspace = true, features = ["global-context", "rand-std"] }
serde_json.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
