[package]
edition = "2021"
name = "strata-bridge-proof-snark"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
ark-bn254.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true
ark-groth16.workspace = true
ark-serialize.workspace = true
bincode.workspace = true
hex.workspace = true
sp1-sdk.workspace = true
sp1-verifier = { workspace = true, features = ["ark"] }
strata-bridge-guest-builder.workspace = true
strata-bridge-proof-protocol.workspace = true
tracing.workspace = true
zkaleido.workspace = true
zkaleido-sp1-groth16-verifier.workspace = true
zkaleido-sp1-host.workspace = true

[dev-dependencies]
