[package]
name = "strata-bridge-counter-proof"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
strata-crypto.workspace = true
strata-primitives.workspace = true

zkaleido.workspace = true
zkaleido-native-adapter.workspace = true

bitcoin.workspace = true
borsh.workspace = true

[dev-dependencies]
tracing.workspace = true
