[package]
name = "strata-bridge-counter-proof"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
strata-crypto.workspace = true
strata-primitives.workspace = true

zkaleido = { git = "https://github.com/alpenlabs/zkaleido", tag = "v0.1.0-alpha-rc13" }
zkaleido-native-adapter = { git = "https://github.com/alpenlabs/zkaleido", tag = "v0.1.0-alpha-rc13" }

bitcoin.workspace = true
borsh.workspace = true

[dev-dependencies]
strata-bridge-common.workspace = true
tracing.workspace = true
