[package]
edition = "2021"
name = "strata-bridge-guest-builder"
version = "0.1.0"

[dependencies]
sp1-sdk = "4.1.3"

[build-dependencies]
sp1-helper = "4.1.3"
sp1-sdk = "4.1.3"

[features]
prover = []
