[package]
edition = "2021"
name = "strata-bridge-guest-builder"
version = "0.1.0"

[lints]
workspace = true

[dependencies]
sp1-sdk = "5.0.0"

[build-dependencies]
sp1-helper = "5.0.0"
sp1-sdk = "5.0.0"

[features]
prover = []
