[package]
edition = "2021"
name = "strata-bridge"
version = "0.1.0"

[[bin]]
name = "strata-bridge"
path = "src/main.rs"

[dependencies]
strata-bridge-agent.workspace = true
strata-bridge-btcio.workspace = true
strata-bridge-db.workspace = true
strata-bridge-primitives.workspace = true
strata-bridge-rpc.workspace = true
strata-bridge-tx-graph.workspace = true
strata-rpc.workspace = true

strata-common.workspace = true

anyhow.workspace = true
async-trait.workspace = true
bincode.workspace = true
bitcoin.workspace = true
chrono.workspace = true
clap.workspace = true
esplora-client.workspace = true
hex.workspace = true
jsonrpsee = { workspace = true, features = ["client", "server"] }
rand.workspace = true
secp256k1 = { workspace = true, features = ["global-context", "rand-std"] }
sqlx.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[features]
mock = ["strata-bridge-agent/mock"]
