name: Compile

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  crate-checks:
    name: Check that crates compile on their own
    runs-on: self-hosted
    timeout-minutes: 90 # cold run takes a lot of time as each crate is compiled separately
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: nightly-2024-07-27
      - uses: taiki-e/install-action@cargo-hack
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Configure sccache
        run: |
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          echo  "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.6
        with:
          version: "v0.8.1" # sccache version

      - name: Install sqlx-cli
        run: cargo install sqlx-cli --locked

      - run: make migrate && cargo hack check --locked
