# Runs `cargo update` periodically.

name: Update Dependencies

on:
  schedule:
    # Run at the second of every month
    - cron: "0 0 2 * *"
  workflow_dispatch: # Needed so we can run it manually

env:
  AUTHOR: Update Cargo.lock Bot <no-reply@alpenlabs.io>
  BRANCH: create-pull-request/automated-cargo-update
  TITLE: "chore(deps): monthly `cargo update`"
  BODY: |
    Automation to keep dependencies in `Cargo.lock` current.

    <details><summary><strong>cargo update log</strong></summary>
    <p>

    ```log
    $cargo_update_log
    ```

    </p>
    </details>

permissions: {}

jobs:
  extract-rust-version:
    name: Extract toolchain version
    runs-on: ubuntu-latest
    outputs:
      nightly-version: ${{ steps.extract-version.outputs.nightly-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Extract Rust version
        id: extract-version
        uses: ./.github/actions/extract-rust-version

  update:
    name: Update
    runs-on: ubuntu-latest
    needs: extract-rust-version
    permissions:
      contents: write # Needed to create commits
      pull-requests: write # Needed to create a PR
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@b95584d8105b9ab200e15821fa671848cf2b7017 # nightly
        with:
          toolchain: ${{ needs.extract-rust-version.outputs.nightly-version }}

      - name: cargo update
        # Remove first line that always just says "Updating crates.io index"
        run: cargo update --color never 2>&1 | sed '/crates.io index/d' | tee -a cargo_update.log

      - name: craft commit message and PR body
        id: msg
        run: |
          cargo_update_log="$(cat cargo_update.log)"
          export cargo_update_log

          {
            echo "commit_message<<EOF"
            echo "$TITLE"
            echo ""
            echo "$cargo_update_log"
            echo ""
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

          {
            echo "body<<EOF"
            echo "$BODY" | envsubst
            echo "EOF"
          } >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7
        with:
          add-paths: ./Cargo.lock
          commit-message: ${{ steps.msg.outputs.commit_message }}
          author: ${{ env.AUTHOR }}
          title: ${{ env.TITLE }}
          body: ${{ steps.msg.outputs.body }}
          branch: ${{ env.BRANCH }}
