name: Docs

on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  extract-rust-version:
    name: Extract toolchain version
    runs-on: ubuntu-latest
    outputs:
      nightly-version: ${{ steps.extract-version.outputs.nightly-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Extract Rust version
        id: extract-version
        uses: $/.github/actions/extract-rust-version

  docs:
    name: Generate docs
    runs-on: ubuntu-latest
    needs: extract-rust-version
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install Rust toolchain
        env:
          RUST_NIGHTLY: ${{ needs.extract-rust-version.outputs.nightly-version }}
        run: |
          rustup toolchain install "$RUST_NIGHTLY" --profile minimal
          rustup default "$RUST_NIGHTLY"

      - name: Rust cache
        uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # v2
        with:
          cache-on-failure: true

      - name: Install FoundationDB
        uses: $/.github/actions/setup-foundationdb # zizmor: ignore[unpinned-uses]

      - name: Install just
        uses: taiki-e/install-action@76c2e6406e52637deed7160d77bded76bd83e06e # v2.87.14
        with:
          tool: just

      - name: Check docs leaving the dependencies out
        run: just rustdocs
